cd \3d\dynam\data\cars\bpp
mkdir bk
copy prpl_a6.bpp bk\
copy prpl_a7.bpp bk\
copy prpl_a2.bpp bk\
copy prpl0014.bpp bk\
copy prpl_a3.bpp bk\
copy prpl0008.bpp bk\
copy prpl0019.bpp bk\
copy prpl0011.bpp bk\
copy prpl0012.bpp bk\
copy prpl0013.bpp bk\
copy prpl0010.bpp bk\
copy prpl_a1.bpp bk\
copy prpl0009.bpp bk\
copy arm0004.bpp bk\
copy arm0005.bpp bk\
copy arm0008.bpp bk\
copy arm0009.bpp bk\
copy exhaust.bpp bk\
copy exhst_tp.bpp bk\

